import { NavLinks } from '@/app/ui/nav-links'
import './globals.css'
import Popup from './popup/page'

import StoreProvider from './StoreProvider'


export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div className='relative'>
          <NavLinks />
          <StoreProvider count={0}> {/* Pass the initial count value here */}
            <main>{children}</main>
            <span
              className='fixed bottom-5 right-5'
            >
              <Popup />
              <div
                className='bg-orange-400 flex items-center text-black justify-center py-2 font-bold hover:cursor-pointer active:scale-75 duration-1000'
                style={{
                  borderRadius: '0 0 10px 10px'
                }}
              >Checkout</div>
            </span>
          </StoreProvider>
        </div>
      </body>
    </html >
  )
}





// import type { Metadata } from "next";
// import localFont from "next/font/local";
// import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
